version: '3'
services:
  datadog-agent:
    image: datadog/agent:latest
    env_file:
      - ~/<your .bashrc or .bash_profile file>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - 127.0.0.1:8126:8126/tcp
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOG_LEVEL=INFO
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_AC_EXCLUDE=name:datadog-agent
  web:
    build: .
    volumes:
      - ./app
    ports:
      - "5000:5000"
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_ANALYTICS_ENABLED=true
    depends_on:
      - datadog-agent